// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: directory_dev_servers.sql

package db

import (
	"context"
	"database/sql"
)

const createDirectoryDevServer = `-- name: CreateDirectoryDevServer :one
INSERT INTO directory_dev_servers (base_directory_id, tmux_session_id, status)
VALUES (?, ?, ?)
RETURNING id, base_directory_id, tmux_session_id, status, created_at, updated_at
`

type CreateDirectoryDevServerParams struct {
	BaseDirectoryID int64  `db:"base_directory_id" json:"base_directory_id"`
	TmuxSessionID   string `db:"tmux_session_id" json:"tmux_session_id"`
	Status          string `db:"status" json:"status"`
}

func (q *Queries) CreateDirectoryDevServer(ctx context.Context, arg CreateDirectoryDevServerParams) (DirectoryDevServer, error) {
	row := q.db.QueryRowContext(ctx, createDirectoryDevServer, arg.BaseDirectoryID, arg.TmuxSessionID, arg.Status)
	var i DirectoryDevServer
	err := row.Scan(
		&i.ID,
		&i.BaseDirectoryID,
		&i.TmuxSessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDirectoryDevServer = `-- name: DeleteDirectoryDevServer :exec
DELETE FROM directory_dev_servers WHERE id = ?
`

func (q *Queries) DeleteDirectoryDevServer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDirectoryDevServer, id)
	return err
}

const deleteDirectoryDevServerByDirectoryID = `-- name: DeleteDirectoryDevServerByDirectoryID :exec
DELETE FROM directory_dev_servers WHERE base_directory_id = ?
`

func (q *Queries) DeleteDirectoryDevServerByDirectoryID(ctx context.Context, baseDirectoryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDirectoryDevServerByDirectoryID, baseDirectoryID)
	return err
}

const getDirectoryDevServer = `-- name: GetDirectoryDevServer :one
SELECT id, base_directory_id, tmux_session_id, status, created_at, updated_at FROM directory_dev_servers
WHERE id = ?
`

func (q *Queries) GetDirectoryDevServer(ctx context.Context, id int64) (DirectoryDevServer, error) {
	row := q.db.QueryRowContext(ctx, getDirectoryDevServer, id)
	var i DirectoryDevServer
	err := row.Scan(
		&i.ID,
		&i.BaseDirectoryID,
		&i.TmuxSessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDirectoryDevServerByDirectoryID = `-- name: GetDirectoryDevServerByDirectoryID :one
SELECT id, base_directory_id, tmux_session_id, status, created_at, updated_at FROM directory_dev_servers
WHERE base_directory_id = ?
`

func (q *Queries) GetDirectoryDevServerByDirectoryID(ctx context.Context, baseDirectoryID int64) (DirectoryDevServer, error) {
	row := q.db.QueryRowContext(ctx, getDirectoryDevServerByDirectoryID, baseDirectoryID)
	var i DirectoryDevServer
	err := row.Scan(
		&i.ID,
		&i.BaseDirectoryID,
		&i.TmuxSessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunningDirectoryDevServers = `-- name: ListRunningDirectoryDevServers :many
SELECT
    dds.id, dds.base_directory_id, dds.tmux_session_id, dds.status, dds.created_at, dds.updated_at,
    bd.path as directory_path,
    bd.base_directory_id as directory_name,
    p.id as project_id,
    p.name as project_name
FROM directory_dev_servers dds
JOIN base_directories bd ON dds.base_directory_id = bd.id
JOIN projects p ON bd.project_id = p.id
WHERE dds.status = 'running'
ORDER BY dds.created_at DESC
`

type ListRunningDirectoryDevServersRow struct {
	ID              int64        `db:"id" json:"id"`
	BaseDirectoryID int64        `db:"base_directory_id" json:"base_directory_id"`
	TmuxSessionID   string       `db:"tmux_session_id" json:"tmux_session_id"`
	Status          string       `db:"status" json:"status"`
	CreatedAt       sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime `db:"updated_at" json:"updated_at"`
	DirectoryPath   string       `db:"directory_path" json:"directory_path"`
	DirectoryName   string       `db:"directory_name" json:"directory_name"`
	ProjectID       int64        `db:"project_id" json:"project_id"`
	ProjectName     string       `db:"project_name" json:"project_name"`
}

func (q *Queries) ListRunningDirectoryDevServers(ctx context.Context) ([]ListRunningDirectoryDevServersRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunningDirectoryDevServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunningDirectoryDevServersRow
	for rows.Next() {
		var i ListRunningDirectoryDevServersRow
		if err := rows.Scan(
			&i.ID,
			&i.BaseDirectoryID,
			&i.TmuxSessionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DirectoryPath,
			&i.DirectoryName,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDirectoryDevServerStatus = `-- name: UpdateDirectoryDevServerStatus :one
UPDATE directory_dev_servers
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, base_directory_id, tmux_session_id, status, created_at, updated_at
`

type UpdateDirectoryDevServerStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateDirectoryDevServerStatus(ctx context.Context, arg UpdateDirectoryDevServerStatusParams) (DirectoryDevServer, error) {
	row := q.db.QueryRowContext(ctx, updateDirectoryDevServerStatus, arg.Status, arg.ID)
	var i DirectoryDevServer
	err := row.Scan(
		&i.ID,
		&i.BaseDirectoryID,
		&i.TmuxSessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
