// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Agent struct {
	ID        int64        `db:"id" json:"id"`
	RootID    int64        `db:"root_id" json:"root_id"`
	Name      string       `db:"name" json:"name"`
	Command   string       `db:"command" json:"command"`
	Params    string       `db:"params" json:"params"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

type BaseDirectory struct {
	ID                        int64        `db:"id" json:"id"`
	ProjectID                 int64        `db:"project_id" json:"project_id"`
	BaseDirectoryID           string       `db:"base_directory_id" json:"base_directory_id"`
	Path                      string       `db:"path" json:"path"`
	GitInitialized            bool         `db:"git_initialized" json:"git_initialized"`
	WorktreeSetupCommands     string       `db:"worktree_setup_commands" json:"worktree_setup_commands"`
	WorktreeTeardownCommands  string       `db:"worktree_teardown_commands" json:"worktree_teardown_commands"`
	DevServerSetupCommands    string       `db:"dev_server_setup_commands" json:"dev_server_setup_commands"`
	DevServerTeardownCommands string       `db:"dev_server_teardown_commands" json:"dev_server_teardown_commands"`
	CreatedAt                 sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt                 sql.NullTime `db:"updated_at" json:"updated_at"`
}

type Project struct {
	ID        int64        `db:"id" json:"id"`
	RootID    int64        `db:"root_id" json:"root_id"`
	Name      string       `db:"name" json:"name"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

type Root struct {
	ID          int64          `db:"id" json:"id"`
	LocalPort   string         `db:"local_port" json:"local_port"`
	ExternalUrl sql.NullString `db:"external_url" json:"external_url"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type Task struct {
	ID          int64         `db:"id" json:"id"`
	ProjectID   int64         `db:"project_id" json:"project_id"`
	Title       string        `db:"title" json:"title"`
	Description string        `db:"description" json:"description"`
	WorktreeID  sql.NullInt64 `db:"worktree_id" json:"worktree_id"`
	CreatedAt   sql.NullTime  `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime  `db:"updated_at" json:"updated_at"`
}

type Worktree struct {
	ID              int64          `db:"id" json:"id"`
	BaseDirectoryID string         `db:"base_directory_id" json:"base_directory_id"`
	Path            string         `db:"path" json:"path"`
	AgentTmuxID     sql.NullString `db:"agent_tmux_id" json:"agent_tmux_id"`
	DevServerTmuxID sql.NullString `db:"dev_server_tmux_id" json:"dev_server_tmux_id"`
	ExternalUrl     sql.NullString `db:"external_url" json:"external_url"`
	CreatedAt       sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime   `db:"updated_at" json:"updated_at"`
}
