// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: remote_ports.sql

package db

import (
	"context"
	"database/sql"
)

const createRemotePort = `-- name: CreateRemotePort :one
INSERT INTO remote_ports (port, tmux_session_id, status)
VALUES (?, ?, ?)
RETURNING id, port, tmux_session_id, external_url, status, created_at, updated_at
`

type CreateRemotePortParams struct {
	Port          int64  `db:"port" json:"port"`
	TmuxSessionID string `db:"tmux_session_id" json:"tmux_session_id"`
	Status        string `db:"status" json:"status"`
}

func (q *Queries) CreateRemotePort(ctx context.Context, arg CreateRemotePortParams) (RemotePort, error) {
	row := q.db.QueryRowContext(ctx, createRemotePort, arg.Port, arg.TmuxSessionID, arg.Status)
	var i RemotePort
	err := row.Scan(
		&i.ID,
		&i.Port,
		&i.TmuxSessionID,
		&i.ExternalUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRemotePort = `-- name: DeleteRemotePort :exec
DELETE FROM remote_ports WHERE id = ?
`

func (q *Queries) DeleteRemotePort(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRemotePort, id)
	return err
}

const getRemotePort = `-- name: GetRemotePort :one
SELECT id, port, tmux_session_id, external_url, status, created_at, updated_at FROM remote_ports
WHERE id = ?
`

func (q *Queries) GetRemotePort(ctx context.Context, id int64) (RemotePort, error) {
	row := q.db.QueryRowContext(ctx, getRemotePort, id)
	var i RemotePort
	err := row.Scan(
		&i.ID,
		&i.Port,
		&i.TmuxSessionID,
		&i.ExternalUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRemotePorts = `-- name: ListActiveRemotePorts :many
SELECT id, port, tmux_session_id, external_url, status, created_at, updated_at FROM remote_ports
WHERE status IN ('starting', 'connected')
ORDER BY created_at DESC
`

func (q *Queries) ListActiveRemotePorts(ctx context.Context) ([]RemotePort, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRemotePorts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemotePort
	for rows.Next() {
		var i RemotePort
		if err := rows.Scan(
			&i.ID,
			&i.Port,
			&i.TmuxSessionID,
			&i.ExternalUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemotePorts = `-- name: ListRemotePorts :many
SELECT id, port, tmux_session_id, external_url, status, created_at, updated_at FROM remote_ports
ORDER BY created_at DESC
`

func (q *Queries) ListRemotePorts(ctx context.Context) ([]RemotePort, error) {
	rows, err := q.db.QueryContext(ctx, listRemotePorts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemotePort
	for rows.Next() {
		var i RemotePort
		if err := rows.Scan(
			&i.ID,
			&i.Port,
			&i.TmuxSessionID,
			&i.ExternalUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRemotePortExternalUrl = `-- name: UpdateRemotePortExternalUrl :one
UPDATE remote_ports
SET external_url = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, port, tmux_session_id, external_url, status, created_at, updated_at
`

type UpdateRemotePortExternalUrlParams struct {
	ExternalUrl sql.NullString `db:"external_url" json:"external_url"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateRemotePortExternalUrl(ctx context.Context, arg UpdateRemotePortExternalUrlParams) (RemotePort, error) {
	row := q.db.QueryRowContext(ctx, updateRemotePortExternalUrl, arg.ExternalUrl, arg.ID)
	var i RemotePort
	err := row.Scan(
		&i.ID,
		&i.Port,
		&i.TmuxSessionID,
		&i.ExternalUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRemotePortStatus = `-- name: UpdateRemotePortStatus :one
UPDATE remote_ports
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, port, tmux_session_id, external_url, status, created_at, updated_at
`

type UpdateRemotePortStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateRemotePortStatus(ctx context.Context, arg UpdateRemotePortStatusParams) (RemotePort, error) {
	row := q.db.QueryRowContext(ctx, updateRemotePortStatus, arg.Status, arg.ID)
	var i RemotePort
	err := row.Scan(
		&i.ID,
		&i.Port,
		&i.TmuxSessionID,
		&i.ExternalUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
