// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_executions.sql

package db

import (
	"context"
	"database/sql"
)

const createTaskExecution = `-- name: CreateTaskExecution :one
INSERT INTO task_executions (task_id, agent_id, status, agent_tmux_id, dev_server_tmux_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id, task_id, agent_id, status, agent_tmux_id, dev_server_tmux_id, created_at, updated_at
`

type CreateTaskExecutionParams struct {
	TaskID          int64          `db:"task_id" json:"task_id"`
	AgentID         int64          `db:"agent_id" json:"agent_id"`
	Status          string         `db:"status" json:"status"`
	AgentTmuxID     sql.NullString `db:"agent_tmux_id" json:"agent_tmux_id"`
	DevServerTmuxID sql.NullString `db:"dev_server_tmux_id" json:"dev_server_tmux_id"`
}

func (q *Queries) CreateTaskExecution(ctx context.Context, arg CreateTaskExecutionParams) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, createTaskExecution,
		arg.TaskID,
		arg.AgentID,
		arg.Status,
		arg.AgentTmuxID,
		arg.DevServerTmuxID,
	)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AgentID,
		&i.Status,
		&i.AgentTmuxID,
		&i.DevServerTmuxID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskExecution = `-- name: DeleteTaskExecution :exec
DELETE FROM task_executions WHERE id = ?
`

func (q *Queries) DeleteTaskExecution(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskExecution, id)
	return err
}

const getTaskExecution = `-- name: GetTaskExecution :one
SELECT id, task_id, agent_id, status, agent_tmux_id, dev_server_tmux_id, created_at, updated_at FROM task_executions
WHERE id = ?
`

func (q *Queries) GetTaskExecution(ctx context.Context, id int64) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, getTaskExecution, id)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AgentID,
		&i.Status,
		&i.AgentTmuxID,
		&i.DevServerTmuxID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskExecutionWithDetails = `-- name: GetTaskExecutionWithDetails :one
SELECT
    te.id, te.task_id, te.agent_id, te.status, te.agent_tmux_id, te.dev_server_tmux_id, te.created_at, te.updated_at,
    t.title as task_title,
    t.description as task_description,
    t.base_directory_id,
    a.name as agent_name,
    a.command as agent_command,
    bd.path as base_directory_path,
    p.id as project_id,
    p.name as project_name
FROM task_executions te
JOIN tasks t ON te.task_id = t.id
JOIN agents a ON te.agent_id = a.id
JOIN base_directories bd ON t.base_directory_id = bd.base_directory_id AND t.project_id = bd.project_id
JOIN projects p ON t.project_id = p.id
WHERE te.id = ?
`

type GetTaskExecutionWithDetailsRow struct {
	ID                int64          `db:"id" json:"id"`
	TaskID            int64          `db:"task_id" json:"task_id"`
	AgentID           int64          `db:"agent_id" json:"agent_id"`
	Status            string         `db:"status" json:"status"`
	AgentTmuxID       sql.NullString `db:"agent_tmux_id" json:"agent_tmux_id"`
	DevServerTmuxID   sql.NullString `db:"dev_server_tmux_id" json:"dev_server_tmux_id"`
	CreatedAt         sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt         sql.NullTime   `db:"updated_at" json:"updated_at"`
	TaskTitle         string         `db:"task_title" json:"task_title"`
	TaskDescription   string         `db:"task_description" json:"task_description"`
	BaseDirectoryID   string         `db:"base_directory_id" json:"base_directory_id"`
	AgentName         string         `db:"agent_name" json:"agent_name"`
	AgentCommand      string         `db:"agent_command" json:"agent_command"`
	BaseDirectoryPath string         `db:"base_directory_path" json:"base_directory_path"`
	ProjectID         int64          `db:"project_id" json:"project_id"`
	ProjectName       string         `db:"project_name" json:"project_name"`
}

func (q *Queries) GetTaskExecutionWithDetails(ctx context.Context, id int64) (GetTaskExecutionWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskExecutionWithDetails, id)
	var i GetTaskExecutionWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AgentID,
		&i.Status,
		&i.AgentTmuxID,
		&i.DevServerTmuxID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskTitle,
		&i.TaskDescription,
		&i.BaseDirectoryID,
		&i.AgentName,
		&i.AgentCommand,
		&i.BaseDirectoryPath,
		&i.ProjectID,
		&i.ProjectName,
	)
	return i, err
}

const getTaskExecutionsByAgentID = `-- name: GetTaskExecutionsByAgentID :many
SELECT id, task_id, agent_id, status, agent_tmux_id, dev_server_tmux_id, created_at, updated_at FROM task_executions
WHERE agent_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetTaskExecutionsByAgentID(ctx context.Context, agentID int64) ([]TaskExecution, error) {
	rows, err := q.db.QueryContext(ctx, getTaskExecutionsByAgentID, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskExecution
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AgentID,
			&i.Status,
			&i.AgentTmuxID,
			&i.DevServerTmuxID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskExecutionsByTaskID = `-- name: GetTaskExecutionsByTaskID :many
SELECT
    te.id, te.task_id, te.agent_id, te.status, te.agent_tmux_id, te.dev_server_tmux_id, te.created_at, te.updated_at,
    a.name as agent_name
FROM task_executions te
JOIN agents a ON te.agent_id = a.id
WHERE te.task_id = ?
ORDER BY te.created_at
`

type GetTaskExecutionsByTaskIDRow struct {
	ID              int64          `db:"id" json:"id"`
	TaskID          int64          `db:"task_id" json:"task_id"`
	AgentID         int64          `db:"agent_id" json:"agent_id"`
	Status          string         `db:"status" json:"status"`
	AgentTmuxID     sql.NullString `db:"agent_tmux_id" json:"agent_tmux_id"`
	DevServerTmuxID sql.NullString `db:"dev_server_tmux_id" json:"dev_server_tmux_id"`
	CreatedAt       sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime   `db:"updated_at" json:"updated_at"`
	AgentName       string         `db:"agent_name" json:"agent_name"`
}

func (q *Queries) GetTaskExecutionsByTaskID(ctx context.Context, taskID int64) ([]GetTaskExecutionsByTaskIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskExecutionsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskExecutionsByTaskIDRow
	for rows.Next() {
		var i GetTaskExecutionsByTaskIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AgentID,
			&i.Status,
			&i.AgentTmuxID,
			&i.DevServerTmuxID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExecutions = `-- name: ListTaskExecutions :many
SELECT
    te.id, te.task_id, te.agent_id, te.status, te.agent_tmux_id, te.dev_server_tmux_id, te.created_at, te.updated_at,
    t.title as task_title,
    a.name as agent_name,
    p.id as project_id,
    p.name as project_name
FROM task_executions te
JOIN tasks t ON te.task_id = t.id
JOIN agents a ON te.agent_id = a.id
JOIN projects p ON t.project_id = p.id
ORDER BY te.created_at DESC
`

type ListTaskExecutionsRow struct {
	ID              int64          `db:"id" json:"id"`
	TaskID          int64          `db:"task_id" json:"task_id"`
	AgentID         int64          `db:"agent_id" json:"agent_id"`
	Status          string         `db:"status" json:"status"`
	AgentTmuxID     sql.NullString `db:"agent_tmux_id" json:"agent_tmux_id"`
	DevServerTmuxID sql.NullString `db:"dev_server_tmux_id" json:"dev_server_tmux_id"`
	CreatedAt       sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime   `db:"updated_at" json:"updated_at"`
	TaskTitle       string         `db:"task_title" json:"task_title"`
	AgentName       string         `db:"agent_name" json:"agent_name"`
	ProjectID       int64          `db:"project_id" json:"project_id"`
	ProjectName     string         `db:"project_name" json:"project_name"`
}

func (q *Queries) ListTaskExecutions(ctx context.Context) ([]ListTaskExecutionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskExecutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskExecutionsRow
	for rows.Next() {
		var i ListTaskExecutionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AgentID,
			&i.Status,
			&i.AgentTmuxID,
			&i.DevServerTmuxID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskTitle,
			&i.AgentName,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExecutionsByTaskID = `-- name: ListTaskExecutionsByTaskID :many
SELECT id, task_id, agent_id, status, agent_tmux_id, dev_server_tmux_id, created_at, updated_at FROM task_executions
WHERE task_id = ?
ORDER BY created_at
`

func (q *Queries) ListTaskExecutionsByTaskID(ctx context.Context, taskID int64) ([]TaskExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTaskExecutionsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskExecution
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AgentID,
			&i.Status,
			&i.AgentTmuxID,
			&i.DevServerTmuxID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskExecutionStatus = `-- name: UpdateTaskExecutionStatus :one
UPDATE task_executions
SET
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, task_id, agent_id, status, agent_tmux_id, dev_server_tmux_id, created_at, updated_at
`

type UpdateTaskExecutionStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateTaskExecutionStatus(ctx context.Context, arg UpdateTaskExecutionStatusParams) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, updateTaskExecutionStatus, arg.Status, arg.ID)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AgentID,
		&i.Status,
		&i.AgentTmuxID,
		&i.DevServerTmuxID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskExecutionTmux = `-- name: UpdateTaskExecutionTmux :one
UPDATE task_executions
SET
    agent_tmux_id = ?,
    dev_server_tmux_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, task_id, agent_id, status, agent_tmux_id, dev_server_tmux_id, created_at, updated_at
`

type UpdateTaskExecutionTmuxParams struct {
	AgentTmuxID     sql.NullString `db:"agent_tmux_id" json:"agent_tmux_id"`
	DevServerTmuxID sql.NullString `db:"dev_server_tmux_id" json:"dev_server_tmux_id"`
	ID              int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateTaskExecutionTmux(ctx context.Context, arg UpdateTaskExecutionTmuxParams) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, updateTaskExecutionTmux, arg.AgentTmuxID, arg.DevServerTmuxID, arg.ID)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AgentID,
		&i.Status,
		&i.AgentTmuxID,
		&i.DevServerTmuxID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
