// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webauthn.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countWebAuthnCredentials = `-- name: CountWebAuthnCredentials :one
SELECT COUNT(*) FROM webauthn_credentials
`

func (q *Queries) CountWebAuthnCredentials(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebAuthnCredentials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebAuthnCredentialsByRpID = `-- name: CountWebAuthnCredentialsByRpID :one
SELECT COUNT(*) FROM webauthn_credentials
WHERE rp_id = ?
`

func (q *Queries) CountWebAuthnCredentialsByRpID(ctx context.Context, rpID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebAuthnCredentialsByRpID, rpID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, expires_at)
VALUES (?, ?)
RETURNING token, expires_at, created_at
`

type CreateSessionParams struct {
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Token, arg.ExpiresAt)
	var i Session
	err := row.Scan(&i.Token, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :one
INSERT INTO webauthn_credentials (id, rp_id, public_key, attestation_type, transport, aaguid, sign_count)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, rp_id, public_key, attestation_type, transport, aaguid, sign_count, created_at
`

type CreateWebAuthnCredentialParams struct {
	ID              string         `db:"id" json:"id"`
	RpID            string         `db:"rp_id" json:"rp_id"`
	PublicKey       []byte         `db:"public_key" json:"public_key"`
	AttestationType string         `db:"attestation_type" json:"attestation_type"`
	Transport       sql.NullString `db:"transport" json:"transport"`
	Aaguid          []byte         `db:"aaguid" json:"aaguid"`
	SignCount       int64          `db:"sign_count" json:"sign_count"`
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRowContext(ctx, createWebAuthnCredential,
		arg.ID,
		arg.RpID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Transport,
		arg.Aaguid,
		arg.SignCount,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.RpID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transport,
		&i.Aaguid,
		&i.SignCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :exec
DELETE FROM webauthn_credentials WHERE id = ?
`

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWebAuthnCredential, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT token, expires_at, created_at FROM sessions
WHERE token = ? AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i Session
	err := row.Scan(&i.Token, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const getWebAuthnCredential = `-- name: GetWebAuthnCredential :one
SELECT id, rp_id, public_key, attestation_type, transport, aaguid, sign_count, created_at FROM webauthn_credentials
WHERE id = ?
`

func (q *Queries) GetWebAuthnCredential(ctx context.Context, id string) (WebauthnCredential, error) {
	row := q.db.QueryRowContext(ctx, getWebAuthnCredential, id)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.RpID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transport,
		&i.Aaguid,
		&i.SignCount,
		&i.CreatedAt,
	)
	return i, err
}

const listWebAuthnCredentials = `-- name: ListWebAuthnCredentials :many
SELECT id, rp_id, public_key, attestation_type, transport, aaguid, sign_count, created_at FROM webauthn_credentials
ORDER BY created_at
`

func (q *Queries) ListWebAuthnCredentials(ctx context.Context) ([]WebauthnCredential, error) {
	rows, err := q.db.QueryContext(ctx, listWebAuthnCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.RpID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Transport,
			&i.Aaguid,
			&i.SignCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebAuthnCredentialsByRpID = `-- name: ListWebAuthnCredentialsByRpID :many
SELECT id, rp_id, public_key, attestation_type, transport, aaguid, sign_count, created_at FROM webauthn_credentials
WHERE rp_id = ?
ORDER BY created_at
`

func (q *Queries) ListWebAuthnCredentialsByRpID(ctx context.Context, rpID string) ([]WebauthnCredential, error) {
	rows, err := q.db.QueryContext(ctx, listWebAuthnCredentialsByRpID, rpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.RpID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Transport,
			&i.Aaguid,
			&i.SignCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebAuthnCredentialSignCount = `-- name: UpdateWebAuthnCredentialSignCount :exec
UPDATE webauthn_credentials
SET sign_count = ?
WHERE id = ?
`

type UpdateWebAuthnCredentialSignCountParams struct {
	SignCount int64  `db:"sign_count" json:"sign_count"`
	ID        string `db:"id" json:"id"`
}

func (q *Queries) UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error {
	_, err := q.db.ExecContext(ctx, updateWebAuthnCredentialSignCount, arg.SignCount, arg.ID)
	return err
}
